### ISSUE TITLE
repeat group

### ISSUE THREAD

**Issue by tamaar-i** [smap-consulting/fieldTask4#1]
Why doesn't the repeat group appear in the fieldTask 6.211and 6.509  when using the relevant opposite odk collect in which it appears
![Screenshot_20220426-033337](https://user-images.githubusercontent.com/104406046/165210619-1cbe9790-5961-4d46-9cd0-53e33b41aca1.png)
![Screenshot_20220426-033409](https://user-images.githubusercontent.com/104406046/165210622-c7a572c4-257c-4c3c-b3b9-aaeae8836c88.png)

**Comment by nap2000** [comment]
Hi @tamaar-i, My apologies for the slow response I was not monitoring this page.  

If this is still an issue can you provide a link to the form that is causing the issue on google sheets.

**Comment by nap2000** [comment]
Closing this as there is not enough information to address it.
